// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('c:/Users/ddark/desenvolvimento/typescript/mobile/contak/node_modules/react');
var { Component } = React;
var ReactNative = require('c:/Users/ddark/desenvolvimento/typescript/mobile/contak/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('contak', appParameters);
});
require('c:/Users/ddark/desenvolvimento/typescript/mobile/contak/index.js');